# Generated by Django 4.2.10 on 2025-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_type', models.CharField(max_length=64)),
                ('params_json', models.JSONField(default=dict)),
                ('summary_json', models.JSONField(default=dict)),
            ],
        ),
    ]
